/**
 * Tests for hippocampusFormat.ts
 * Covers: output structure, charter handling, secret sanitisation,
 * linkedFolder.path redaction, optional sections, asset filtering, and edge cases.
 */

import {
  generateHippocampusMarkdown,
  generateDefaultCharter,
  HIPPOCAMPUS_SCHEMA_VERSION,
} from '../utils/hippocampusFormat';
import type { ProjectMemory } from '../types/memphant-types';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function makeProject(overrides: Partial<ProjectMemory> = {}): ProjectMemory {
  return {
    schema_version: 1,
    id: 'test_hippocampus',
    name: 'My SaaS App',
    summary: 'A SaaS product for project context management.',
    goals: ['Launch MVP', 'Get first 10 customers'],
    rules: ['Ship fast', 'Talk to users weekly'],
    decisions: [
      { decision: 'Use Tauri for desktop', rationale: 'Small bundle, native performance' },
    ],
    currentState: 'Pre-launch. MVP is 80% done.',
    nextSteps: ['Set up Stripe', 'Write landing page copy'],
    openQuestions: ['What pricing model?'],
    importantAssets: ['src/main.ts', 'src/store.ts'],
    aiInstructions: 'Help me think like a product founder.',
    changelog: [
      {
        timestamp: new Date().toISOString(),
        field: 'general',
        action: 'added',
        summary: 'Project created',
        source: 'app',
      },
    ],
    checkpoints: [],
    platformState: {},
    ...overrides,
  };
}

// Build secret-like strings at runtime so GitHub push protection
// does not flag the repository contents themselves.
function joinParts(...parts: string[]): string {
  return parts.join('');
}

function makeOpenAiKey(): string {
  return joinParts('sk-', 'AbCdEfGhIjKlMnOpQrStUv1234567890');
}

function makeAnthropicKey(): string {
  return joinParts(
    'sk-ant-api03-',
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz012345',
  );
}

function makeGitHubToken(): string {
  return joinParts('ghp_', 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghij');
}

function makeStripeLiveKey(): string {
  return joinParts('sk', '_live_', '1234567890abcdefghijklmnop');
}

function getSection(output: string, heading: string): string {
  const escapedHeading = heading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = output.match(
    new RegExp(`## ${escapedHeading}\\n\\n([\\s\\S]*?)(?=\\n## |\\n---|$)`),
  );

  return match?.[1]?.trim() ?? '';
}

function getSectionBullets(output: string, heading: string): string[] {
  return getSection(output, heading)
    .split('\n')
    .filter((line) => line.startsWith('- '));
}

// ─── Structure ────────────────────────────────────────────────────────────────

describe('generateHippocampusMarkdown - structure', () => {
  it('returns a non-empty string', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(typeof output).toBe('string');
    expect(output.length).toBeGreaterThan(0);
  });

  it('includes the protocol header comment', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).toContain('hippocampus.md — Memory Core File Protocol v1');
    expect(output).toContain('Generated by Memephant. Edit in Memephant or regenerate.');
  });

  it('includes the schema version in the header', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).toContain(`hippocampus/${HIPPOCAMPUS_SCHEMA_VERSION}`);
  });

  it('HIPPOCAMPUS_SCHEMA_VERSION is 1.0', () => {
    expect(HIPPOCAMPUS_SCHEMA_VERSION).toBe('1.0');
  });

  it('includes the project id in the header', () => {
    const output = generateHippocampusMarkdown(makeProject({ id: 'proj_xyz' }));
    expect(output).toContain('project-id: proj_xyz');
  });

  it('includes a generated timestamp in the header', () => {
    const before = new Date().toISOString().slice(0, 10);
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).toContain(before);
  });

  it('includes the project name as the main heading', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).toContain('# My SaaS App — Memory Core');
  });

  it('includes Project Identity', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).toContain('## Project Identity');
    expect(output).toContain('Name: My SaaS App');
    expect(output).toContain('Summary: A SaaS product for project context management.');
  });

  it('always includes the Charter section', () => {
    const output = generateHippocampusMarkdown(makeProject({ projectCharter: 'Ship safely.' }));
    expect(output).toContain('## Charter');
  });

  it('includes the Current State section when currentState is present', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).toContain('## Current State');
    expect(output).toContain('Pre-launch. MVP is 80% done.');
  });

  it('includes Goals', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).toContain('## Goals');
    expect(output).toContain('Launch MVP');
    expect(output).toContain('Get first 10 customers');
  });

  it('includes Rules', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).toContain('## Rules');
    expect(output).toContain('Ship fast');
  });

  it('includes Decisions with rationale', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).toContain('## Decisions');
    expect(output).toContain('Use Tauri for desktop');
    expect(output).toContain('Small bundle, native performance');
  });

  it('includes Next Steps', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).toContain('## Next Steps');
    expect(output).toContain('Set up Stripe');
  });

  it('includes Open Questions', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).toContain('## Open Questions');
    expect(output).toContain('What pricing model?');
  });

  it('includes Important Assets', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).toContain('## Important Assets');
    expect(output).toContain('src/main.ts');
  });

  it('includes safety Boundaries', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).toContain('## Boundaries');
    expect(output).toContain('Never expose secrets, tokens, credentials, or private local paths.');
  });

  it('includes the footer with protocol name', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).toContain('Memory Core File Protocol v1');
    expect(output).toContain('Edit the Memory Core in Memephant or regenerate');
  });
});

// ─── Charter ──────────────────────────────────────────────────────────────────

describe('generateHippocampusMarkdown - charter', () => {
  it('includes charter content when present', () => {
    const output = generateHippocampusMarkdown(
      makeProject({ projectCharter: 'Always prefer minimal safe edits.' }),
    );

    expect(output).toContain('## Charter');
    expect(output).toContain('Always prefer minimal safe edits.');
  });

  it('generates default charter from project fields when charter is empty string', () => {
    const output = generateHippocampusMarkdown(makeProject({ projectCharter: '' }));

    expect(output).toContain('## Charter');
    expect(output).toContain('Auto-generated');
    expect(output).toContain('Launch MVP');
  });

  it('generates default charter when charter is undefined', () => {
    const project = makeProject();
    delete (project as Partial<ProjectMemory>).projectCharter;

    const output = generateHippocampusMarkdown(project);

    expect(output).toContain('## Charter');
    expect(output).toContain('Auto-generated');
    expect(output).toContain('Pre-launch. MVP is 80% done.');
  });

  it('generates default charter when charter is whitespace only', () => {
    const output = generateHippocampusMarkdown(makeProject({ projectCharter: '   ' }));

    expect(output).not.toContain('(no charter set)');
    expect(output).toContain('Auto-generated');
  });

  it('user-authored charter takes precedence over auto-generated content', () => {
    const output = generateHippocampusMarkdown(
      makeProject({ projectCharter: 'Always prefer minimal safe edits.' }),
    );

    expect(output).toContain('Always prefer minimal safe edits.');
    expect(output).not.toContain('Auto-generated');
  });

  it('trims leading and trailing whitespace from the charter', () => {
    const output = generateHippocampusMarkdown(
      makeProject({ projectCharter: '\n  Prefer safe changes.  \n' }),
    );

    expect(output).toContain('Prefer safe changes.');
  });
});

// ─── generateDefaultCharter unit tests ───────────────────────────────────────

describe('generateDefaultCharter', () => {
  it('includes the auto-generated label when project fields exist', () => {
    const result = generateDefaultCharter(makeProject());
    expect(result).toContain('Auto-generated');
  });

  it('includes currentState in synthesised text', () => {
    const result = generateDefaultCharter(makeProject({ currentState: 'MVP is live.' }));
    expect(result).toContain('MVP is live.');
  });

  it('falls back to summary when currentState is empty', () => {
    const result = generateDefaultCharter(
      makeProject({ currentState: '', summary: 'A SaaS product.' }),
    );

    expect(result).toContain('A SaaS product.');
  });

  it('includes goals in synthesised text', () => {
    const result = generateDefaultCharter(makeProject({ goals: ['Reach 100 users', 'Ship v2'] }));

    expect(result).toContain('Reach 100 users');
    expect(result).toContain('Ship v2');
  });

  it('uses primary goals label for a single goal', () => {
    const result = generateDefaultCharter(makeProject({ goals: ['Ship MVP'] }));
    expect(result).toContain('Primary goals: Ship MVP.');
  });

  it('uses primary goals label for multiple goals', () => {
    const result = generateDefaultCharter(makeProject({ goals: ['Ship MVP', 'Get users'] }));
    expect(result).toContain('Primary goals: Ship MVP; Get users.');
  });

  it('includes rules in synthesised text', () => {
    const result = generateDefaultCharter(makeProject({ rules: ['Ship fast', 'Talk to users'] }));

    expect(result).toContain('Ship fast');
    expect(result).toContain('Talk to users');
  });

  it('includes key decisions text only, not rationale', () => {
    const result = generateDefaultCharter(
      makeProject({
        decisions: [{ decision: 'Use Tauri', rationale: 'Fast binaries' }],
      }),
    );

    expect(result).toContain('Use Tauri');
    expect(result).not.toContain('Fast binaries');
  });

  it('returns a safe baseline charter when project has no content at all', () => {
    const result = generateDefaultCharter(
      makeProject({
        summary: '',
        currentState: '',
        goals: [],
        rules: [],
        decisions: [],
      }),
    );

    expect(result).toContain('This project should be handled with small, safe, user-controlled changes.');
    expect(result).toContain('Protect secrets, tokens, credentials, and private local paths.');
    expect(result).not.toContain('Auto-generated from project fields');
  });
});

// ─── Optional sections ────────────────────────────────────────────────────────

describe('generateHippocampusMarkdown - optional sections', () => {
  it('includes In Progress when set', () => {
    const output = generateHippocampusMarkdown(
      makeProject({ inProgress: ['Implementing auth flow'] }),
    );

    expect(output).toContain('## In Progress');
    expect(output).toContain('Implementing auth flow');
  });

  it('omits In Progress section when not set', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).not.toContain('## In Progress');
  });

  it('omits In Progress section when set to empty array', () => {
    const output = generateHippocampusMarkdown(makeProject({ inProgress: [] }));
    expect(output).not.toContain('## In Progress');
  });

  it('includes Last Session Summary when set', () => {
    const output = generateHippocampusMarkdown(
      makeProject({ lastSessionSummary: 'Finished the Stripe integration.' }),
    );

    expect(output).toContain('## Last Session Summary');
    expect(output).toContain('Finished the Stripe integration.');
  });

  it('omits Last Session Summary when not set', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).not.toContain('## Last Session Summary');
  });

  it('includes singular Open Question when set', () => {
    const output = generateHippocampusMarkdown(
      makeProject({ openQuestion: 'Should we launch as freemium or free trial?' }),
    );

    expect(output).toMatch(/^## Open Question$/m);
    expect(output).toContain('Should we launch as freemium or free trial?');
  });

  it('omits singular Open Question when not set', () => {
    const output = generateHippocampusMarkdown(makeProject());

    expect(output).not.toMatch(/^## Open Question$/m);
    expect(output).toContain('## Open Questions');
  });

  it('includes Stack when detectedStack is set', () => {
    const output = generateHippocampusMarkdown(
      makeProject({ detectedStack: ['TypeScript', 'React', 'Vite'] }),
    );

    expect(output).toContain('## Stack');
    expect(output).toContain('TypeScript');
    expect(output).toContain('React');
    expect(output).toContain('Vite');
  });

  it('omits Stack when detectedStack is not set', () => {
    const output = generateHippocampusMarkdown(makeProject());
    expect(output).not.toContain('## Stack');
  });

  it('omits Rules section when rules array is empty', () => {
    const output = generateHippocampusMarkdown(makeProject({ rules: [] }));
    expect(output).not.toContain('## Rules');
  });
});

// ─── Important Assets hardening ───────────────────────────────────────────────

describe('generateHippocampusMarkdown - important asset hardening', () => {
  it('normalizes backslashes to forward slashes', () => {
    const output = generateHippocampusMarkdown(
      makeProject({
        importantAssets: ['public-site\\index.html', 'server\\server.js'],
      }),
    );

    expect(output).toContain('public-site/index.html');
    expect(output).toContain('server/server.js');
    expect(output).not.toContain('public-site\\index.html');
  });

  it('caps important assets to 20 useful entries', () => {
    const assets = Array.from({ length: 30 }, (_, index) => `src/file-${index + 1}.ts`);
    const output = generateHippocampusMarkdown(makeProject({ importantAssets: assets }));
    const bullets = getSectionBullets(output, 'Important Assets');

    expect(bullets).toHaveLength(20);
  });

  it('omits suspicious asset filenames', () => {
    const output = generateHippocampusMarkdown(
      makeProject({
        importantAssets: [
          'public-site/index.html',
          'pwordsec.txt',
          '.env',
          'server/private-key.pem',
          'server/token-cache.json',
        ],
      }),
    );

    expect(output).toContain('public-site/index.html');
    expect(output).not.toContain('pwordsec.txt');
    expect(output).not.toContain('.env');
    expect(output).not.toContain('private-key.pem');
    expect(output).not.toContain('token-cache.json');
  });

  it('omits mojibake or broken filenames', () => {
    const output = generateHippocampusMarkdown(
      makeProject({
        importantAssets: [
          'public-site/index.html',
          'docs/2┤®┼ÈÔ· BRIGHTFOUNDRY ÈÃ÷ MONTHLY CHECK-I.txt',
          'docs/¡â¯╔ WEBSITE & APP DEVELOPMENT BUSINESS.txt',
        ],
      }),
    );

    expect(output).toContain('public-site/index.html');
    expect(output).not.toContain('2┤®┼ÈÔ·');
    expect(output).not.toContain('¡â¯╔');
  });

  it('omits generic noisy scratch files', () => {
    const output = generateHippocampusMarkdown(
      makeProject({
        importantAssets: [
          'public-site/index.html',
          'TASK NAME.txt',
          'TASK NAME7.txt',
          'docs/Untitled.txt',
        ],
      }),
    );

    expect(output).toContain('public-site/index.html');
    expect(output).not.toContain('TASK NAME.txt');
    expect(output).not.toContain('TASK NAME7.txt');
    expect(output).not.toContain('Untitled.txt');
  });

  it('deduplicates important assets case-insensitively', () => {
    const output = generateHippocampusMarkdown(
      makeProject({
        importantAssets: ['public-site/index.html', 'PUBLIC-SITE/INDEX.HTML'],
      }),
    );
    const bullets = getSectionBullets(output, 'Important Assets');

    expect(bullets).toHaveLength(1);
  });
});

// ─── Secret sanitisation ──────────────────────────────────────────────────────

describe('generateHippocampusMarkdown - secret sanitisation', () => {
  it('redacts OpenAI keys in currentState', () => {
    const secret = makeOpenAiKey();
    const output = generateHippocampusMarkdown(makeProject({ currentState: `Key: ${secret}` }));

    expect(output).not.toContain(secret);
    expect(output).toContain('[REDACTED]');
  });

  it('redacts Anthropic keys in goals', () => {
    const secret = makeAnthropicKey();
    const output = generateHippocampusMarkdown(makeProject({ goals: [`Use ${secret}`] }));

    expect(output).not.toContain(secret);
    expect(output).toContain('[REDACTED]');
  });

  it('redacts GitHub tokens in next steps', () => {
    const secret = makeGitHubToken();
    const output = generateHippocampusMarkdown(
      makeProject({ nextSteps: [`Token: ${secret}`] }),
    );

    expect(output).not.toContain(secret);
    expect(output).toContain('[REDACTED]');
  });

  it('redacts secrets inside the project charter', () => {
    const secret = makeOpenAiKey();
    const output = generateHippocampusMarkdown(
      makeProject({ projectCharter: `Never expose ${secret}` }),
    );

    expect(output).not.toContain(secret);
    expect(output).toContain('[REDACTED]');
  });

  it('redacts secrets in open questions', () => {
    const secret = makeAnthropicKey();
    const output = generateHippocampusMarkdown(
      makeProject({ openQuestions: [`Should we use ${secret}?`] }),
    );

    expect(output).not.toContain(secret);
    expect(output).toContain('[REDACTED]');
  });

  it('redacts secrets in decision rationale', () => {
    const secret = makeGitHubToken();
    const output = generateHippocampusMarkdown(
      makeProject({
        decisions: [{ decision: 'Use CI', rationale: `Token: ${secret}` }],
      }),
    );

    expect(output).not.toContain(secret);
    expect(output).toContain('[REDACTED]');
  });

  it('redacts Stripe live keys', () => {
    const secret = makeStripeLiveKey();
    const output = generateHippocampusMarkdown(
      makeProject({ currentState: `Stripe: ${secret}` }),
    );

    expect(output).not.toContain(secret);
    expect(output).toContain('[REDACTED]');
  });

  it('always redacts database connection strings because strict patterns are always active', () => {
    const secret = 'postgres://user:pass@host:5432/mydb';
    const output = generateHippocampusMarkdown(
      makeProject({ currentState: `DB: ${secret}` }),
    );

    expect(output).not.toContain(secret);
    expect(output).toContain('[REDACTED]');
  });

  it('does not redact normal project content', () => {
    const output = generateHippocampusMarkdown(makeProject());

    expect(output).toContain('My SaaS App');
    expect(output).toContain('Launch MVP');
    expect(output).toContain('Use Tauri for desktop');
    expect(output).not.toContain('[REDACTED]');
  });
});

// ─── linkedFolder path exclusion ──────────────────────────────────────────────

describe('generateHippocampusMarkdown - linkedFolder.path exclusion', () => {
  it('never includes a POSIX linked folder path', () => {
    const project = makeProject({
      linkedFolder: {
        path: '/Users/kris/secret/project-path',
        scanHash: 'abc',
        lastScannedAt: '',
      },
    });
    const output = generateHippocampusMarkdown(project);

    expect(output).not.toContain('/Users/kris/secret/project-path');
  });

  it('never includes a Windows-style linked folder path', () => {
    const project = makeProject({
      linkedFolder: {
        path: 'C:\\Users\\thoma\\private\\memephant',
        scanHash: 'abc',
        lastScannedAt: '',
      },
    });
    const output = generateHippocampusMarkdown(project);

    expect(output).not.toContain('C:\\Users\\thoma\\private\\memephant');
    expect(output).not.toContain('C:/Users/thoma/private/memephant');
  });

  it('redacts the linked folder path embedded in the charter', () => {
    const linkedPath = 'C:\\Users\\kris\\private\\memephant';
    const project = makeProject({
      projectCharter: `Do not expose ${linkedPath}`,
      linkedFolder: { path: linkedPath, scanHash: 'abc', lastScannedAt: '' },
    });
    const output = generateHippocampusMarkdown(project);

    expect(output).not.toContain(linkedPath);
    expect(output).toContain('[REDACTED]');
  });

  it('redacts the linked folder path embedded in current state', () => {
    const linkedPath = '/Users/kris/projects/my-app';
    const project = makeProject({
      currentState: `Working in ${linkedPath}`,
      linkedFolder: { path: linkedPath, scanHash: 'abc', lastScannedAt: '' },
    });
    const output = generateHippocampusMarkdown(project);

    expect(output).not.toContain(linkedPath);
  });

  it('redacts forward-slash variant of a Windows path', () => {
    const winPath = 'C:\\Users\\thoma\\secret';
    const project = makeProject({
      currentState: 'Path is C:/Users/thoma/secret',
      linkedFolder: { path: winPath, scanHash: 'abc', lastScannedAt: '' },
    });
    const output = generateHippocampusMarkdown(project);

    expect(output).not.toContain('C:/Users/thoma/secret');
  });
});

// ─── Edge cases ───────────────────────────────────────────────────────────────

describe('generateHippocampusMarkdown - edge cases', () => {
  it('handles a project with all empty arrays gracefully', () => {
    const project = makeProject({
      goals: [],
      rules: [],
      decisions: [],
      nextSteps: [],
      openQuestions: [],
      importantAssets: [],
    });

    expect(() => generateHippocampusMarkdown(project)).not.toThrow();
    const output = generateHippocampusMarkdown(project);
    expect(output.length).toBeGreaterThan(0);
  });

  it('omits Current State when currentState is empty', () => {
    const output = generateHippocampusMarkdown(makeProject({ currentState: '' }));

    expect(output).not.toMatch(/^## Current State$/m);
    expect(output).not.toContain('(none)');
  });

  it('handles a very long charter without crashing', () => {
    const project = makeProject({ projectCharter: 'A'.repeat(5000) });
    expect(() => generateHippocampusMarkdown(project)).not.toThrow();
  });

  it('handles special characters in the project name', () => {
    const project = makeProject({ name: '<script>alert("xss")</script>' });
    const output = generateHippocampusMarkdown(project);

    expect(output).toBeDefined();
    expect(output.length).toBeGreaterThan(0);
  });

  it('handles a decision with no rationale', () => {
    const project = makeProject({
      decisions: [{ decision: 'Use TypeScript' }],
    });
    const output = generateHippocampusMarkdown(project);

    expect(output).toContain('Use TypeScript');
    expect(output).not.toContain('Rationale: undefined');
  });

  it('produces a string with consistent section count for same input', () => {
    const project = makeProject();
    const out1 = generateHippocampusMarkdown(project);
    const out2 = generateHippocampusMarkdown(project);

    const stripTs = (value: string) =>
      value.replace(/generated: [0-9TZ:.-]+/, 'generated: [TS]');

    expect(stripTs(out1).split('\n').length).toBe(stripTs(out2).split('\n').length);
  });

  it('does not include linkedFolder scanHash or lastScannedAt', () => {
    const project = makeProject({
      linkedFolder: {
        path: '/tmp/proj',
        scanHash: 'deadbeef12345',
        lastScannedAt: '2026-01-01T00:00:00Z',
      },
    });
    const output = generateHippocampusMarkdown(project);

    expect(output).not.toContain('deadbeef12345');
    expect(output).not.toContain('2026-01-01T00:00:00Z');
    expect(output).not.toContain('/tmp/proj');
  });
});
