/**
 * Tests for prefrontalFormat.ts
 * Covers: output structure, working rules, current state, last session summary,
 * inProgress, nextSteps cap, openQuestion, placeholder filtering, deduplication,
 * secret sanitisation, linkedFolder.path redaction, optional sections, lastAiSession,
 * recent checkpoint, and referenced files (mentioned assets).
 */

import {
  generatePrefrontalMarkdown,
  PREFRONTAL_SCHEMA_VERSION,
} from '../utils/prefrontalFormat';
import type { ProjectMemory, ProjectCheckpointSnapshot } from '../types/memphant-types';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function makeProject(overrides: Partial<ProjectMemory> = {}): ProjectMemory {
  return {
    schema_version: 1,
    id: 'test_prefrontal',
    name: 'My SaaS App',
    summary: 'A SaaS product for project context management.',
    goals: ['Launch MVP', 'Get first 10 customers'],
    rules: ['Ship fast', 'Talk to users weekly'],
    decisions: [
      { decision: 'Use Tauri for desktop', rationale: 'Small bundle, native performance' },
    ],
    currentState: 'Pre-launch. MVP is 80% done.',
    nextSteps: ['Set up Stripe', 'Write landing page copy'],
    openQuestions: ['What pricing model?'],
    importantAssets: ['src/main.ts', 'src/store.ts'],
    aiInstructions: 'Help me think like a product founder.',
    changelog: [
      {
        timestamp: new Date().toISOString(),
        field: 'general',
        action: 'added',
        summary: 'Project created',
        source: 'app',
      },
    ],
    checkpoints: [],
    platformState: {},
    ...overrides,
  };
}

// Build secret-like strings at runtime so GitHub push protection
// does not flag the repository contents themselves.
function joinParts(...parts: string[]): string {
  return parts.join('');
}

function makeOpenAiKey(): string {
  return joinParts('sk-', 'AbCdEfGhIjKlMnOpQrStUv1234567890');
}

function makeAnthropicKey(): string {
  return joinParts(
    'sk-ant-api03-',
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz012345',
  );
}

function makeGitHubToken(): string {
  return joinParts('ghp_', 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghij');
}

function makeStripeLiveKey(): string {
  return joinParts('sk', '_live_', '1234567890abcdefghijklmnop');
}

function getSection(output: string, heading: string): string {
  const escapedHeading = heading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = output.match(
    new RegExp(`## ${escapedHeading}\\n\\n([\\s\\S]*?)(?=\\n## |\\n---|$)`),
  );
  return match?.[1]?.trim() ?? '';
}

function getSectionBullets(output: string, heading: string): string[] {
  return getSection(output, heading)
    .split('\n')
    .filter((line) => line.startsWith('- '));
}

// ─── Structure ────────────────────────────────────────────────────────────────

describe('generatePrefrontalMarkdown - structure', () => {
  it('returns a non-empty string', () => {
    const output = generatePrefrontalMarkdown(makeProject());
    expect(typeof output).toBe('string');
    expect(output.length).toBeGreaterThan(0);
  });

  it('includes the protocol header comment', () => {
    const output = generatePrefrontalMarkdown(makeProject());
    expect(output).toContain('prefrontal.md — Working Memory File Protocol v1');
    expect(output).toContain('Generated by Memephant. Edit in Memephant or regenerate.');
  });

  it('includes the schema version in the header', () => {
    const output = generatePrefrontalMarkdown(makeProject());
    expect(output).toContain(`prefrontal/${PREFRONTAL_SCHEMA_VERSION}`);
  });

  it('PREFRONTAL_SCHEMA_VERSION is 1.0', () => {
    expect(PREFRONTAL_SCHEMA_VERSION).toBe('1.0');
  });

  it('includes the project id in the header', () => {
    const output = generatePrefrontalMarkdown(makeProject({ id: 'proj_xyz' }));
    expect(output).toContain('project-id: proj_xyz');
  });

  it('includes a generated timestamp in the header', () => {
    const before = new Date().toISOString().slice(0, 10);
    const output = generatePrefrontalMarkdown(makeProject());
    expect(output).toContain(before);
  });

  it('includes the project name as the main heading', () => {
    const output = generatePrefrontalMarkdown(makeProject());
    expect(output).toContain('# My SaaS App — Working Memory');
  });

  it('includes the footer with protocol name', () => {
    const output = generatePrefrontalMarkdown(makeProject());
    expect(output).toContain('Working Memory File Protocol v1');
    expect(output).toContain('Regenerate when session context changes');
  });

  it('ends with a horizontal rule before the footer', () => {
    const output = generatePrefrontalMarkdown(makeProject());
    expect(output).toContain('\n---\n');
  });
});

// ─── Working Rules ────────────────────────────────────────────────────────────

describe('generatePrefrontalMarkdown - working rules', () => {
  it('always includes the Working Rules section', () => {
    const output = generatePrefrontalMarkdown(makeProject());
    expect(output).toContain('## Working Rules');
  });

  it('names prefrontal.md as short-term working memory', () => {
    const output = generatePrefrontalMarkdown(makeProject());
    expect(output).toContain('prefrontal.md');
    expect(output).toContain('short-term working memory');
  });

  it('names hippocampus.md as stable long-term memory', () => {
    const output = generatePrefrontalMarkdown(makeProject());
    expect(output).toContain('hippocampus.md');
    expect(output).toContain('stable long-term memory');
  });

  it('instructs AIs not to infer long-term direction from this file', () => {
    const output = generatePrefrontalMarkdown(makeProject());
    expect(output).toContain('Do not infer long-term project direction from this file');
  });

  it('describes this file as volatile', () => {
    const output = generatePrefrontalMarkdown(makeProject());
    expect(output).toContain('volatile');
  });

  it('includes Working Rules even when all optional fields are absent', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        currentState: '',
        lastSessionSummary: undefined,
        inProgress: [],
        nextSteps: [],
        openQuestion: undefined,
      }),
    );
    expect(output).toContain('## Working Rules');
  });
});

// ─── Current State ────────────────────────────────────────────────────────────

describe('generatePrefrontalMarkdown - current state', () => {
  it('includes Current State when set', () => {
    const output = generatePrefrontalMarkdown(makeProject());
    expect(output).toContain('## Current State');
    expect(output).toContain('Pre-launch. MVP is 80% done.');
  });

  it('omits Current State when empty string', () => {
    const output = generatePrefrontalMarkdown(makeProject({ currentState: '' }));
    expect(output).not.toContain('## Current State');
  });

  it('omits Current State when whitespace only', () => {
    const output = generatePrefrontalMarkdown(makeProject({ currentState: '   ' }));
    expect(output).not.toContain('## Current State');
  });

  it('omits Current State when it is a placeholder value', () => {
    // Placeholder prefix: "Write 1-2 sentences describing what is true right now after this session."
    const output = generatePrefrontalMarkdown(
      makeProject({
        currentState: 'Write 1-2 sentences describing what is true right now after this session.',
      }),
    );
    expect(output).not.toContain('## Current State');
  });
});

// ─── Last Session Summary ─────────────────────────────────────────────────────

describe('generatePrefrontalMarkdown - last session summary', () => {
  it('includes Last Session Summary when set', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({ lastSessionSummary: 'Completed the auth flow and pushed to staging.' }),
    );
    expect(output).toContain('## Last Session Summary');
    expect(output).toContain('Completed the auth flow and pushed to staging.');
  });

  it('omits Last Session Summary when not set', () => {
    const output = generatePrefrontalMarkdown(makeProject({ lastSessionSummary: undefined }));
    expect(output).not.toContain('## Last Session Summary');
  });

  it('omits Last Session Summary when it is a placeholder value', () => {
    // Placeholder prefix: "Write 2-4 sentences recapping exactly what happened in this session."
    const output = generatePrefrontalMarkdown(
      makeProject({
        lastSessionSummary:
          'Write 2-4 sentences recapping exactly what happened in this session.',
      }),
    );
    expect(output).not.toContain('## Last Session Summary');
  });
});

// ─── In Progress ──────────────────────────────────────────────────────────────

describe('generatePrefrontalMarkdown - in progress', () => {
  it('includes In Progress when items are set', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({ inProgress: ['Fix auth bug', 'Update landing page'] }),
    );
    expect(output).toContain('## In Progress');
    expect(output).toContain('Fix auth bug');
    expect(output).toContain('Update landing page');
  });

  it('omits In Progress when the array is empty', () => {
    const output = generatePrefrontalMarkdown(makeProject({ inProgress: [] }));
    expect(output).not.toContain('## In Progress');
  });

  it('omits In Progress when not set', () => {
    const output = generatePrefrontalMarkdown(makeProject({ inProgress: undefined }));
    expect(output).not.toContain('## In Progress');
  });

  it('caps In Progress at 5 items', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        inProgress: ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
      }),
    );
    const bullets = getSectionBullets(output, 'In Progress');
    expect(bullets.length).toBe(5);
  });

  it('filters placeholder values from In Progress', () => {
    // Exact placeholder: "list only things actively being worked on right now not done not future"
    const output = generatePrefrontalMarkdown(
      makeProject({
        inProgress: [
          'List only things actively being worked on right now, not done, not future.',
          'Real task',
        ],
      }),
    );
    const section = getSection(output, 'In Progress');
    expect(section).toContain('Real task');
    expect(section).not.toContain('List only things actively being worked on right now');
  });

  it('deduplicates In Progress items case-insensitively', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({ inProgress: ['Fix auth bug', 'fix auth bug', 'FIX AUTH BUG', 'Other task'] }),
    );
    const bullets = getSectionBullets(output, 'In Progress');
    expect(bullets.filter((b) => b.toLowerCase().includes('fix auth bug')).length).toBe(1);
    expect(bullets.length).toBe(2);
  });
});

// ─── Immediate Next Steps ─────────────────────────────────────────────────────

describe('generatePrefrontalMarkdown - immediate next steps', () => {
  it('includes Immediate Next Steps when items are set', () => {
    const output = generatePrefrontalMarkdown(makeProject());
    expect(output).toContain('## Immediate Next Steps');
    expect(output).toContain('Set up Stripe');
  });

  it('omits Immediate Next Steps when the array is empty', () => {
    const output = generatePrefrontalMarkdown(makeProject({ nextSteps: [] }));
    expect(output).not.toContain('## Immediate Next Steps');
  });

  it('caps Immediate Next Steps at 7 items', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        nextSteps: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
      }),
    );
    const bullets = getSectionBullets(output, 'Immediate Next Steps');
    expect(bullets.length).toBe(7);
  });

  it('includes exactly 7 items when exactly 7 are provided', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        nextSteps: ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
      }),
    );
    const bullets = getSectionBullets(output, 'Immediate Next Steps');
    expect(bullets.length).toBe(7);
  });

  it('filters placeholder values from Immediate Next Steps', () => {
    // Exact placeholder: "list the immediate next actions that should happen after this session"
    const output = generatePrefrontalMarkdown(
      makeProject({
        nextSteps: [
          'List the immediate next actions that should happen after this session.',
          'Actual step',
        ],
      }),
    );
    const section = getSection(output, 'Immediate Next Steps');
    expect(section).toContain('Actual step');
    expect(section).not.toContain('List the immediate next actions that should happen');
  });

  it('deduplicates Immediate Next Steps case-insensitively', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        nextSteps: ['Deploy to prod', 'Deploy to prod', 'DEPLOY TO PROD', 'Write tests'],
      }),
    );
    const bullets = getSectionBullets(output, 'Immediate Next Steps');
    expect(bullets.filter((b) => b.toLowerCase().includes('deploy to prod')).length).toBe(1);
    expect(bullets.length).toBe(2);
  });
});

// ─── Open Question ────────────────────────────────────────────────────────────

describe('generatePrefrontalMarkdown - open question', () => {
  it('includes Open Question when set', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({ openQuestion: 'Should we support Windows first or macOS?' }),
    );
    expect(output).toContain('## Open Question');
    expect(output).toContain('Should we support Windows first or macOS?');
  });

  it('omits Open Question when not set', () => {
    const output = generatePrefrontalMarkdown(makeProject({ openQuestion: undefined }));
    expect(output).not.toContain('## Open Question');
  });

  it('omits Open Question when empty string', () => {
    const output = generatePrefrontalMarkdown(makeProject({ openQuestion: '' }));
    expect(output).not.toContain('## Open Question');
  });

  it('omits Open Question when it is a placeholder value', () => {
    // Exact placeholder: "the single most important unresolved question or decision needed to move forward"
    const output = generatePrefrontalMarkdown(
      makeProject({
        openQuestion:
          'The single most important unresolved question or decision needed to move forward.',
      }),
    );
    expect(output).not.toContain('## Open Question');
  });
});

// ─── Last AI Session ──────────────────────────────────────────────────────────

describe('generatePrefrontalMarkdown - last AI session', () => {
  it('includes Last AI Session when lastAiSession is set', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        lastAiSession: {
          platform: 'claude',
          mode: 'continue',
          sessionAt: '2024-03-15T10:00:00.000Z',
          userTaskSummary: 'Built the export formatter.',
        },
      }),
    );
    expect(output).toContain('## Last AI Session');
    expect(output).toContain('claude');
    expect(output).toContain('continue');
    expect(output).toContain('Built the export formatter.');
  });

  it('omits Last AI Session when lastAiSession is not set', () => {
    const output = generatePrefrontalMarkdown(makeProject({ lastAiSession: undefined }));
    expect(output).not.toContain('## Last AI Session');
  });

  it('includes switch reason when set', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        lastAiSession: {
          platform: 'chatgpt',
          mode: 'review',
          sessionAt: '2024-03-15T10:00:00.000Z',
          userSwitchReason: 'Switching to Claude for coding.',
        },
      }),
    );
    expect(output).toContain('Switch reason: Switching to Claude for coding.');
  });

  it('omits task summary line when userTaskSummary is empty', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        lastAiSession: {
          platform: 'claude',
          mode: 'continue',
          sessionAt: '2024-03-15T10:00:00.000Z',
        },
      }),
    );
    expect(output).toContain('## Last AI Session');
    expect(output).not.toContain('Task:');
  });
});

// ─── Recent Checkpoint ────────────────────────────────────────────────────────

describe('generatePrefrontalMarkdown - recent checkpoint', () => {
  it('includes Recent Checkpoint when checkpoints are present', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        checkpoints: [
          {
            id: 'cp1',
            platform: 'claude',
            timestamp: '2024-03-15T10:00:00.000Z',
            summary: 'Finished auth module.',
            snapshot: {} as unknown as ProjectCheckpointSnapshot,
            hash: 'abc123',
          },
        ],
      }),
    );
    expect(output).toContain('## Recent Checkpoint');
    expect(output).toContain('Finished auth module.');
  });

  it('omits Recent Checkpoint when checkpoints array is empty', () => {
    const output = generatePrefrontalMarkdown(makeProject({ checkpoints: [] }));
    expect(output).not.toContain('## Recent Checkpoint');
  });

  it('uses the most recent checkpoint when multiple exist', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        checkpoints: [
          {
            id: 'cp1',
            platform: 'claude',
            timestamp: '2024-01-01T10:00:00.000Z',
            summary: 'Older checkpoint.',
            snapshot: {} as unknown as ProjectCheckpointSnapshot,
            hash: 'aaa',
          },
          {
            id: 'cp2',
            platform: 'chatgpt',
            timestamp: '2024-03-15T10:00:00.000Z',
            summary: 'Newer checkpoint.',
            snapshot: {} as unknown as ProjectCheckpointSnapshot,
            hash: 'bbb',
          },
        ],
      }),
    );
    expect(output).toContain('Newer checkpoint.');
    expect(output).not.toContain('Older checkpoint.');
  });

  it('omits Recent Checkpoint when latest checkpoint has empty summary', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        checkpoints: [
          {
            id: 'cp1',
            platform: 'claude',
            timestamp: '2024-03-15T10:00:00.000Z',
            summary: '',
            snapshot: {} as unknown as ProjectCheckpointSnapshot,
            hash: 'abc123',
          },
        ],
      }),
    );
    expect(output).not.toContain('## Recent Checkpoint');
  });
});

// ─── Referenced Files ─────────────────────────────────────────────────────────

describe('generatePrefrontalMarkdown - referenced files', () => {
  it('includes Referenced Files for assets mentioned in context fields', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        currentState: 'Working on src/main.ts right now.',
        importantAssets: ['src/main.ts', 'src/store.ts'],
      }),
    );
    expect(output).toContain('## Referenced Files');
    expect(output).toContain('src/main.ts');
  });

  it('omits assets not mentioned in context fields', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        currentState: 'Working on src/main.ts right now.',
        importantAssets: ['src/main.ts', 'src/unrelated.ts'],
      }),
    );
    const section = getSection(output, 'Referenced Files');
    expect(section).toContain('src/main.ts');
    expect(section).not.toContain('src/unrelated.ts');
  });

  it('omits Referenced Files when no assets are mentioned in context fields', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        currentState: 'Working on a general cleanup.',
        nextSteps: ['Write tests'],
        importantAssets: ['src/obscure-file.ts'],
      }),
    );
    expect(output).not.toContain('## Referenced Files');
  });

  it('caps Referenced Files at 10 items', () => {
    const assets = Array.from({ length: 15 }, (_, i) => `src/file${i}.ts`);
    const contextMentions = assets.map((a) => a).join(' ');
    const output = generatePrefrontalMarkdown(
      makeProject({
        currentState: contextMentions,
        importantAssets: assets,
      }),
    );
    const bullets = getSectionBullets(output, 'Referenced Files');
    expect(bullets.length).toBeLessThanOrEqual(10);
  });
});

// ─── Empty sections omitted ───────────────────────────────────────────────────

describe('generatePrefrontalMarkdown - omits empty sections', () => {
  it('produces a minimal output with only header, title, working rules, and footer when all optional fields absent', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({
        currentState: '',
        lastSessionSummary: undefined,
        inProgress: [],
        nextSteps: [],
        openQuestion: undefined,
        lastAiSession: undefined,
        checkpoints: [],
        importantAssets: [],
      }),
    );
    expect(output).toContain('## Working Rules');
    expect(output).not.toContain('## Current State');
    expect(output).not.toContain('## Last Session Summary');
    expect(output).not.toContain('## In Progress');
    expect(output).not.toContain('## Immediate Next Steps');
    expect(output).not.toContain('## Open Question');
    expect(output).not.toContain('## Last AI Session');
    expect(output).not.toContain('## Recent Checkpoint');
    expect(output).not.toContain('## Referenced Files');
  });
});

// ─── Secret sanitisation ──────────────────────────────────────────────────────

describe('generatePrefrontalMarkdown - secret sanitisation', () => {
  it('redacts OpenAI API keys from currentState', () => {
    const key = makeOpenAiKey();
    const output = generatePrefrontalMarkdown(
      makeProject({ currentState: `Using ${key} for testing.` }),
    );
    expect(output).not.toContain(key);
    expect(output).toContain('[REDACTED]');
  });

  it('redacts Anthropic API keys from lastSessionSummary', () => {
    const key = makeAnthropicKey();
    const output = generatePrefrontalMarkdown(
      makeProject({ lastSessionSummary: `Token: ${key}` }),
    );
    expect(output).not.toContain(key);
    expect(output).toContain('[REDACTED]');
  });

  it('redacts GitHub tokens from inProgress items', () => {
    const token = makeGitHubToken();
    const output = generatePrefrontalMarkdown(
      makeProject({ inProgress: [`Auth with ${token}`] }),
    );
    expect(output).not.toContain(token);
    expect(output).toContain('[REDACTED]');
  });

  it('redacts Stripe live keys from nextSteps items', () => {
    const key = makeStripeLiveKey();
    const output = generatePrefrontalMarkdown(
      makeProject({ nextSteps: [`Set up payments using ${key}`] }),
    );
    expect(output).not.toContain(key);
    expect(output).toContain('[REDACTED]');
  });

  it('redacts OpenAI keys from openQuestion', () => {
    const key = makeOpenAiKey();
    const output = generatePrefrontalMarkdown(
      makeProject({ openQuestion: `Should we use ${key} in prod?` }),
    );
    expect(output).not.toContain(key);
    expect(output).toContain('[REDACTED]');
  });

  it('redacts secrets from lastAiSession userTaskSummary', () => {
    const key = makeGitHubToken();
    const output = generatePrefrontalMarkdown(
      makeProject({
        lastAiSession: {
          platform: 'claude',
          mode: 'continue',
          sessionAt: '2024-03-15T10:00:00.000Z',
          userTaskSummary: `Set up token: ${key}`,
        },
      }),
    );
    expect(output).not.toContain(key);
    expect(output).toContain('[REDACTED]');
  });
});

// ─── linkedFolder.path redaction ─────────────────────────────────────────────

describe('generatePrefrontalMarkdown - linkedFolder.path redaction', () => {
  it('redacts the linkedFolder path from currentState', () => {
    const path = 'C:\\Users\\alice\\Documents\\MyProject';
    const output = generatePrefrontalMarkdown(
      makeProject({
        linkedFolder: { path },
        currentState: `Located at ${path} on disk.`,
      }),
    );
    expect(output).not.toContain(path);
    expect(output).toContain('[REDACTED]');
  });

  it('redacts the linkedFolder path with forward slashes', () => {
    const path = 'C:\\Users\\alice\\Documents\\MyProject';
    const forwardSlash = path.replace(/\\/g, '/');
    const output = generatePrefrontalMarkdown(
      makeProject({
        linkedFolder: { path },
        currentState: `Located at ${forwardSlash} on disk.`,
      }),
    );
    expect(output).not.toContain(forwardSlash);
  });

  it('does not include the linkedFolder path anywhere in output', () => {
    const path = '/home/alice/projects/my-saas';
    const output = generatePrefrontalMarkdown(
      makeProject({
        linkedFolder: { path },
        currentState: 'Working on the dashboard.',
        lastSessionSummary: `Project at ${path}.`,
        inProgress: [`Editing files under ${path}`],
      }),
    );
    expect(output).not.toContain(path);
  });

  it('outputs normally when linkedFolder is not set', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({ linkedFolder: undefined }),
    );
    expect(output).toContain('## Working Rules');
    expect(output).toContain('Pre-launch. MVP is 80% done.');
  });
});

// ─── Edge cases ───────────────────────────────────────────────────────────────

describe('generatePrefrontalMarkdown - edge cases', () => {
  it('trims leading/trailing whitespace from currentState', () => {
    const output = generatePrefrontalMarkdown(
      makeProject({ currentState: '\n  Almost ready to ship.  \n' }),
    );
    expect(output).toContain('Almost ready to ship.');
  });

  it('handles a project with only a name and id', () => {
    const minimal = {
      schema_version: 1,
      id: 'minimal',
      name: 'Minimal Project',
      summary: '',
      goals: [],
      rules: [],
      decisions: [],
      currentState: '',
      nextSteps: [],
      openQuestions: [],
      importantAssets: [],
      aiInstructions: '',
      changelog: [],
      checkpoints: [],
      platformState: {},
    } as ProjectMemory;

    const output = generatePrefrontalMarkdown(minimal);
    expect(output).toContain('# Minimal Project — Working Memory');
    expect(output).toContain('## Working Rules');
  });

  it('sanitises the project name in the title', () => {
    const key = makeOpenAiKey();
    const output = generatePrefrontalMarkdown(makeProject({ name: `Project ${key}` }));
    expect(output).not.toContain(key);
  });

  it('does not include Goals, Rules, or Decisions sections (those belong in hippocampus.md)', () => {
    const output = generatePrefrontalMarkdown(makeProject());
    expect(output).not.toContain('## Goals');
    expect(output).not.toContain('## Rules');
    expect(output).not.toContain('## Decisions');
  });
});


