/**
 * Context Passport Generator
 *
 * Produces a clean, safe, portable snapshot of a project's context
 * in four formats: generic Markdown, ChatGPT, Claude, and Codex.
 *
 * SAFETY RULES (non-negotiable):
 *  - Secrets are redacted using the same patterns as exportFormatters.ts
 *  - linkedFolder.path is NEVER included in any output
 *  - No project data is mutated
 *  - RESPONSE_FORMAT / memphant_update instructions are NOT appended
 *    (a passport is for handoff context, not a live AI session)
 */

import type { ProjectMemory, Decision, ChangelogEntry } from '../types/memphant-types';

// ─── Types ─────────────────────────────────────────────────────────────────

export type PassportFormat = 'markdown' | 'chatgpt' | 'claude' | 'codex';

export interface ContextPassport {
  projectId: string;
  projectName: string;
  generatedAt: string;
  formats: Record<PassportFormat, string>;
}

// ─── Sanitization ──────────────────────────────────────────────────────────
// Mirrors the STANDARD_PATTERNS from exportFormatters.ts.
// Kept inline so this module has no runtime dependency on that file.

const SECRET_PATTERNS: RegExp[] = [
  /sk-[A-Za-z0-9]{20,}/g,
  /sk-ant-[A-Za-z0-9_-]{20,}/g,
  /AKIA[0-9A-Z]{16}/g,
  /ghp_[A-Za-z0-9]{36}/g,
  /github_pat_[A-Za-z0-9_]{82}/g,
  /xoxb-[A-Za-z0-9-]+/g,
  /xoxp-[A-Za-z0-9-]+/g,
  /sk_live_[A-Za-z0-9]{24,}/g,
  /AIza[0-9A-Za-z_-]{35}/g,
  /hf_[A-Za-z0-9]{30,}/g,
  /-----BEGIN [A-Z ]+ KEY-----/g,
  /eyJ[A-Za-z0-9+/=]{20,}/g,
];

function sanitize(text: string): string {
  let out = text;
  for (const pattern of SECRET_PATTERNS) {
    out = out.replace(pattern, '[REDACTED]');
  }
  return out;
}

function sanitizeList(items: string[]): string[] {
  return items.map(sanitize);
}

/** Strip the linked-folder path from text. Never let it leak into exports. */
function redactFolderPath(text: string, project: ProjectMemory): string {
  const path = project.linkedFolder?.path;
  if (!path) return text;

  const variants = [path, path.replace(/\\/g, '/'), path.replace(/\//g, '\\')];
  return variants.reduce(
    (out, v) => (v ? out.split(v).join('[REDACTED]') : out),
    text,
  );
}

function clean(text: string, project: ProjectMemory): string {
  return redactFolderPath(sanitize(text), project);
}

// ─── Formatting helpers ────────────────────────────────────────────────────

function bulletList(items: string[], project: ProjectMemory, indent = ''): string {
  const safe = sanitizeList(items).map((i) => redactFolderPath(i, project));
  if (!safe.length) return `${indent}_(none)_`;
  return safe.map((i) => `${indent}- ${i}`).join('\n');
}

function numberedList(items: string[], project: ProjectMemory): string {
  const safe = sanitizeList(items).map((i) => redactFolderPath(i, project));
  if (!safe.length) return '_(none)_';
  return safe.map((i, idx) => `${idx + 1}. ${i}`).join('\n');
}

function formatDecisions(decisions: Decision[], project: ProjectMemory, indent = ''): string {
  if (!decisions.length) return `${indent}_(none)_`;
  return decisions
    .map((d) => {
      const lines = [`${indent}- ${clean(d.decision, project)}`];
      if (d.rationale) {
        lines.push(`${indent}  _Rationale: ${clean(d.rationale, project)}_`);
      }
      return lines.join('\n');
    })
    .join('\n');
}

function formatChangelog(entries: ChangelogEntry[], limit = 8): string {
  if (!entries.length) return '_(no recent changes recorded)_';
  return entries
    .slice(-limit)
    .map((e) => {
      const date = e.timestamp ? e.timestamp.slice(0, 10) : '';
      return `- [${date}] **${e.field}** ${e.action}: ${sanitize(e.summary)}`;
    })
    .join('\n');
}

const SAFE_EXPORT_NOTES = `## ⚠️ Safe Export Notes

- Secrets, \`.env\` values, and API keys have been excluded.
- Local folder paths have been excluded.
- This passport is intended for safe AI handoff only.
- **Please review before pasting into another AI tool.**`;

// ─── Format builders ────────────────────────────────────────────────────────

function buildMarkdown(project: ProjectMemory, generatedAt: string): string {
  const lines: string[] = [];

  lines.push(`# Context Passport: ${sanitize(project.name)}`);
  lines.push('');
  lines.push(`_Generated by Memephant · ${generatedAt}_`);
  lines.push('');
  lines.push('---');
  lines.push('');

  lines.push(`## Purpose`);
  lines.push(clean(project.summary || '_(not set)_', project));
  lines.push('');

  lines.push(`## Current State`);
  lines.push(clean(project.currentState || '_(not set)_', project));
  lines.push('');

  if (project.inProgress && project.inProgress.length > 0) {
    lines.push(`## In Progress`);
    lines.push(bulletList(project.inProgress, project));
    lines.push('');
  }

  lines.push(`## Goals`);
  lines.push(numberedList(project.goals, project));
  lines.push('');

  lines.push(`## Key Decisions`);
  lines.push(formatDecisions(project.decisions, project));
  lines.push('');

  lines.push(`## Rules to Follow`);
  lines.push(bulletList(project.rules, project));
  lines.push('');

  if (project.importantAssets.length > 0) {
    lines.push(`## Important Files & Assets`);
    lines.push(bulletList(project.importantAssets, project));
    lines.push('');
  }

  lines.push(`## What Changed Recently`);
  lines.push(formatChangelog(project.changelog ?? []));
  lines.push('');

  lines.push(`## Open Questions`);
  lines.push(bulletList(project.openQuestions, project));
  lines.push('');

  if (project.lastSessionSummary) {
    lines.push(`## Last Session Summary`);
    lines.push(clean(project.lastSessionSummary, project));
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(SAFE_EXPORT_NOTES);

  return lines.join('\n');
}

function buildChatGPT(project: ProjectMemory): string {
  const lines: string[] = [];

  lines.push(`# Context Passport: ${sanitize(project.name)}`);
  lines.push('');
  lines.push(
    `I'm sharing my project context so you can pick up exactly where I left off. ` +
    `Please read this fully before responding.`,
  );
  lines.push('');
  lines.push('---');
  lines.push('');

  lines.push(`## Purpose`);
  lines.push(clean(project.summary || '_(not set)_', project));
  lines.push('');

  lines.push(`## Current State`);
  lines.push(clean(project.currentState || '_(not set)_', project));
  lines.push('');

  if (project.inProgress && project.inProgress.length > 0) {
    lines.push(`## In Progress`);
    lines.push(bulletList(project.inProgress, project));
    lines.push('');
  }

  lines.push(`## Goals`);
  lines.push(numberedList(project.goals, project));
  lines.push('');

  lines.push(`## Key Decisions`);
  lines.push(formatDecisions(project.decisions, project));
  lines.push('');

  lines.push(`## Rules to Follow`);
  lines.push(bulletList(project.rules, project));
  lines.push('');

  if (project.importantAssets.length > 0) {
    lines.push(`## Important Files & Assets`);
    lines.push(bulletList(project.importantAssets, project));
    lines.push('');
  }

  lines.push(`## What Changed Recently`);
  lines.push(formatChangelog(project.changelog ?? []));
  lines.push('');

  lines.push(`## Open Questions`);
  lines.push(bulletList(project.openQuestions, project));
  lines.push('');

  if (project.lastSessionSummary) {
    lines.push(`## Last Session Summary`);
    lines.push(clean(project.lastSessionSummary, project));
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(
    `**Please continue working on this project from the current state above.** ` +
    `Ask me what I need help with if it's not already clear from the open questions.`,
  );
  lines.push('');
  lines.push(SAFE_EXPORT_NOTES);

  return lines.join('\n');
}

function buildClaude(project: ProjectMemory, generatedAt: string): string {
  const lines: string[] = [];

  lines.push(`<context_passport>`);
  lines.push(`  <project>${sanitize(project.name)}</project>`);
  lines.push(`  <generated>${generatedAt}</generated>`);
  lines.push(`  <note>This is a safe project context export from Memephant. Please review and continue from where I left off.</note>`);
  lines.push('');

  lines.push(`  <purpose>`);
  lines.push(`    ${clean(project.summary || '(not set)', project)}`);
  lines.push(`  </purpose>`);
  lines.push('');

  lines.push(`  <current_state>`);
  lines.push(`    ${clean(project.currentState || '(not set)', project)}`);
  lines.push(`  </current_state>`);
  lines.push('');

  if (project.inProgress && project.inProgress.length > 0) {
    lines.push(`  <in_progress>`);
    project.inProgress.forEach((item) => {
      lines.push(`    - ${clean(item, project)}`);
    });
    lines.push(`  </in_progress>`);
    lines.push('');
  }

  lines.push(`  <goals>`);
  project.goals.forEach((g, i) => {
    lines.push(`    ${i + 1}. ${clean(g, project)}`);
  });
  if (!project.goals.length) lines.push(`    (none)`);
  lines.push(`  </goals>`);
  lines.push('');

  lines.push(`  <key_decisions>`);
  if (project.decisions.length > 0) {
    project.decisions.forEach((d) => {
      lines.push(`    - ${clean(d.decision, project)}`);
      if (d.rationale) lines.push(`      Rationale: ${clean(d.rationale, project)}`);
    });
  } else {
    lines.push(`    (none)`);
  }
  lines.push(`  </key_decisions>`);
  lines.push('');

  lines.push(`  <rules>`);
  project.rules.forEach((r) => lines.push(`    - ${clean(r, project)}`));
  if (!project.rules.length) lines.push(`    (none)`);
  lines.push(`  </rules>`);
  lines.push('');

  if (project.importantAssets.length > 0) {
    lines.push(`  <important_assets>`);
    project.importantAssets.forEach((a) => lines.push(`    - ${clean(a, project)}`));
    lines.push(`  </important_assets>`);
    lines.push('');
  }

  lines.push(`  <recent_changes>`);
  const recentChangelog = (project.changelog ?? []).slice(-8);
  if (recentChangelog.length > 0) {
    recentChangelog.forEach((e) => {
      const date = e.timestamp ? e.timestamp.slice(0, 10) : '';
      lines.push(`    - [${date}] ${e.field} ${e.action}: ${sanitize(e.summary)}`);
    });
  } else {
    lines.push(`    (no recent changes recorded)`);
  }
  lines.push(`  </recent_changes>`);
  lines.push('');

  lines.push(`  <open_questions>`);
  project.openQuestions.forEach((q) => lines.push(`    - ${clean(q, project)}`));
  if (!project.openQuestions.length) lines.push(`    (none)`);
  lines.push(`  </open_questions>`);
  lines.push('');

  if (project.lastSessionSummary) {
    lines.push(`  <last_session_summary>`);
    lines.push(`    ${clean(project.lastSessionSummary, project)}`);
    lines.push(`  </last_session_summary>`);
    lines.push('');
  }

  lines.push(`  <safe_export_notes>`);
  lines.push(`    - Secrets, .env values, and API keys have been excluded.`);
  lines.push(`    - Local folder paths have been excluded.`);
  lines.push(`    - This passport is for safe AI handoff only.`);
  lines.push(`  </safe_export_notes>`);
  lines.push('');

  lines.push(`</context_passport>`);
  lines.push('');
  lines.push(
    `Please review the context above and continue working on this project from the current state. ` +
    `Ask me what I'd like help with if the open questions don't already make it clear.`,
  );

  return lines.join('\n');
}

function buildCodex(project: ProjectMemory, generatedAt: string): string {
  const lines: string[] = [];

  lines.push(`PROJECT: ${sanitize(project.name)}`);
  lines.push(`GENERATED: ${generatedAt}`);
  if (project.githubRepo) lines.push(`REPO: ${project.githubRepo}`);
  if (project.detectedStack && project.detectedStack.length > 0) {
    lines.push(`STACK: ${sanitize(project.detectedStack.join(', '))}`);
  }
  lines.push('');

  lines.push(`STATUS: ${clean(project.currentState || '(not set)', project)}`);
  lines.push('');

  if (project.inProgress && project.inProgress.length > 0) {
    lines.push(`IN_PROGRESS:`);
    project.inProgress.forEach((item) => lines.push(`  - ${clean(item, project)}`));
    lines.push('');
  }

  lines.push(`GOALS:`);
  project.goals.forEach((g) => lines.push(`  - ${clean(g, project)}`));
  if (!project.goals.length) lines.push(`  (none)`);
  lines.push('');

  lines.push(`RULES:`);
  project.rules.forEach((r) => lines.push(`  - ${clean(r, project)}`));
  if (!project.rules.length) lines.push(`  (none)`);
  lines.push('');

  lines.push(`DECISIONS:`);
  if (project.decisions.length > 0) {
    project.decisions.forEach((d) => {
      lines.push(`  - ${clean(d.decision, project)}`);
      if (d.rationale) lines.push(`    (${clean(d.rationale, project)})`);
    });
  } else {
    lines.push(`  (none)`);
  }
  lines.push('');

  if (project.importantAssets.length > 0) {
    lines.push(`IMPORTANT_FILES:`);
    project.importantAssets.forEach((a) => lines.push(`  - ${clean(a, project)}`));
    lines.push('');
  }

  lines.push(`NEXT_STEPS:`);
  project.nextSteps.forEach((s) => lines.push(`  - ${clean(s, project)}`));
  if (!project.nextSteps.length) lines.push(`  (none)`);
  lines.push('');

  lines.push(`OPEN_QUESTIONS:`);
  project.openQuestions.forEach((q) => lines.push(`  - ${clean(q, project)}`));
  if (!project.openQuestions.length) lines.push(`  (none)`);
  lines.push('');

  lines.push(`RECENT_CHANGES:`);
  const recentChangelog = (project.changelog ?? []).slice(-5);
  if (recentChangelog.length > 0) {
    recentChangelog.forEach((e) => {
      const date = e.timestamp ? e.timestamp.slice(0, 10) : '';
      lines.push(`  - [${date}] ${e.field} ${e.action}: ${sanitize(e.summary)}`);
    });
  } else {
    lines.push(`  (none recorded)`);
  }
  lines.push('');

  lines.push(`# Safe export notes`);
  lines.push(`# - Secrets, .env values, and API keys excluded`);
  lines.push(`# - Local folder paths excluded`);
  lines.push(`# - Review before using in a live coding session`);

  return lines.join('\n');
}

// ─── Public API ────────────────────────────────────────────────────────────

/**
 * Generates a Context Passport for the given project.
 * Pure function — does not mutate the project or any store.
 */
export function generateContextPassport(project: ProjectMemory): ContextPassport {
  const generatedAt = new Date().toLocaleString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return {
    projectId: project.id,
    projectName: sanitize(project.name),
    generatedAt,
    formats: {
      markdown: buildMarkdown(project, generatedAt),
      chatgpt: buildChatGPT(project),
      claude: buildClaude(project, generatedAt),
      codex: buildCodex(project, generatedAt),
    },
  };
}
